version: "3.8"

services:
  backend:
    build: ./backend
    image: adaptive_honeypot-backend:latest
    container_name: adaptive_honeypot-backend-1
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - REDIS_URL=${REDIS_URL}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend:ro
      - ./backend/ml_model:/home/appuser/.config/AdaptiveHoneypot/models
      - ./backend/logs:/app/backend/logs
      - ./data:/data
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - ah_net


  redis:
    image: redis:7-alpine
    container_name: adaptive_honeypot-redis-1
    restart: unless-stopped
    networks:
      - ah_net

  nginx:
    image: nginx:stable-alpine
    container_name: adaptive_honeypot-nginx-1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # optional: if you build frontend static files:
      # - ./frontend/dist:/usr/share/nginx/html/dashboard:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ah_net

networks:
  ah_net:
    driver: bridge
